services:

  api:
    build: .
    ports:
      - "8000:8000"

    volumes:
      - .:/app

    command:
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: pharmaml
      POSTGRES_USER: pharmaml
      POSTGRES_PASSWORD: pharmaml
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: